<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright (c) 2013. Knowledge Media Institute - The Open University
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->

<wsdl:definitions xmlns:sawsdl="http://www.w3.org/ns/sawsdl" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                  xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:tns="http://maps.google.com/" targetNamespace="http://maps.google.com/">
    <wsdl:documentation>This is a WSDL 1.1 comment that has been created for a RESTful service for evaluation and
        testing purposes.
        It is not guaranteed to be correct or appropriate.
    </wsdl:documentation>
    <wsdl:types>
        <xsd:schema elementFormDefault="qualified" targetNamespace="http://maps.google.com/">
            <xsd:annotation>This type information has been semi-automatically generated. It properly represents the
                semantics of the service's parameters, but is not guaranteed to precisely match the schema actually used
                by the service.
            </xsd:annotation>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="Google_Static_Maps_APIHttpGetIn">
        <wsdl:part name="center" type="xsd:string"
                   sawsdl:modelReference="http://fusion.cs.uni-jena.de/geographydataset.owl#RectangularGeographicArea">
            <wsdl:documentation>The geographic location of the center of the map to be returned.</wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="zoom" type="xsd:string">
            <wsdl:documentation>The zoom level of the map.</wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="image_size" type="xsd:string">
            <wsdl:documentation>The size of the map image in pixels (maximum size is 640x640)</wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="format" type="xsd:string">
            <wsdl:documentation>The format of the map image. Either gif, jpg or png32. Optional, gif is default.
            </wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="maptype" type="xsd:string">
            <wsdl:documentation>defines the type of map to construct, either roadmap, or mobile (larger features and
                text fonts). This parameter is optional, roadmap is the default.
            </wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="markers" type="xsd:string"
                   sawsdl:modelReference="http://iserve.kmi.open.ac.uk/2010/05/s3eval/data.rdfs#PointOfInterest">
            <wsdl:documentation>Define one or more markers to attach to the image at specified locations. This optional
                parameter takes a string of marker definitions separated by the pipe character (|). Note that if you
                supply markers for a map, you do not need to specify the (normally required) center and zoom parameters.
            </wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="Path" type="xsd:string"
                   sawsdl:modelReference="http://fusion.cs.uni-jena.de/geographydataset.owl#Polyline">
            <wsdl:documentation>Optional. Defines a single path of two or more connected points to overlay on the image
                at specified locations. This parameter takes a string of point definitions separated by the pipe
                character (|). Note that if you supply a path for a map, you do not need to specify the (normally
                required) center and zoom parameters.
            </wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="span" type="xsd:string">
            <wsdl:documentation>(optional) defines a minimum viewport for the map image expressed as a latitude and
                longitude pair. The static map service takes this value and produces a map of the proper zoom level to
                include the entire provided span value from the map's center point. Note that the resulting map may
                include larger bounds for either latitude or longitude depending on the rectangular dimensions of the
                map. If zoom is specified, span is ignored.
            </wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="frame" type="xsd:string">
            <wsdl:documentation>(optional) specifies that the resulting image should be framed with a colored blue
                border. The frame consists of a 5 pixel, 55% opacity blue border.
            </wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="hl" type="xsd:string">
            <wsdl:documentation>(optional) defines the language to use for display of labels on map tiles. Note that
                this paramater is only supported for some country tiles; if the specific language requested is not
                supported for the tile set, then the default language will be used.
            </wsdl:documentation>
        </wsdl:part>
        <wsdl:part name="key" type="xsd:string">
            <wsdl:documentation>(required) identifies the Maps API key for the domain on which this URL request takes
                place.
            </wsdl:documentation>
        </wsdl:part>
    </wsdl:message>
    <wsdl:message name="Google_Static_Maps_APIHttpGetOut">
        <wsdl:part name="Body" type="xsd:base64Binary"
                   sawsdl:modelReference="http://fusion.cs.uni-jena.de/geographydataset.owl#Map">
            <wsdl:documentation></wsdl:documentation>
        </wsdl:part>
    </wsdl:message>
    <wsdl:portType name="Google_Static_Maps_APIHttpGet">
        <wsdl:operation name="Google_Static_Maps_API"
                        sawsdl:modelReference="http://www.w3.org/ns/wsdl-extensions#SafeInteraction">
            <wsdl:documentation>The Google Static Maps API lets you embed a Google Maps image on your webpage without
                requiring JavaScript or any dynamic page loading. The Google Static Map service creates your map based
                on URL parameters sent through a standard HTTP request and returns the map as an image you can display
                on your web page.
            </wsdl:documentation>
            <wsdl:input message="tns:Google_Static_Maps_APIHttpGetIn"/>
            <wsdl:output message="tns:Google_Static_Maps_APIHttpGetOut"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="Google_Static_Maps_APIHttpGet" type="tns:Google_Static_Maps_APIHttpGet">
        <http:binding verb="GET"/>
        <wsdl:operation name="Google_Static_Maps_API">
            <http:operation location="staticmap"/>
            <wsdl:input>
                <http:urlEncoded/>
            </wsdl:input>
            <wsdl:output>
                <mime:content type="image/jpeg" part="Body"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service sawsdl:modelReference=" http://iserve.kmi.open.ac.uk/2010/05/s3eval/func.rdfs#MappingService"
                  name="Google_Static_Maps_API">
        <wsdl:port name="Google_Static_Maps_APIHttpGet" binding="tns:Google_Static_Maps_APIHttpGet">
            <http:address location="http://maps.google.com/"/>
        </wsdl:port>

    </wsdl:service>
</wsdl:definitions>
