<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="AffyArrayQualityAnalysis_pollInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="AffyArrayQualityAnalysis_pollOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="AffyArrayQualityAnalysis_pollPortType">
          <wsdl:operation name="AffyArrayQualityAnalysis_poll">
                 <wsdl:input message="tns:AffyArrayQualityAnalysis_pollInput"/>
                 <wsdl:output message="tns:AffyArrayQualityAnalysis_pollOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="AffyArrayQualityAnalysis_pollBinding" type="tns:AffyArrayQualityAnalysis_pollPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="AffyArrayQualityAnalysis_poll"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#AffyArrayQualityAnalysis_poll' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="AffyArrayQualityAnalysis_pollService">
          <wsdl:documentation>Authority: nugo-r.bioinformatics.nl  -  Checks the status of an asynchronous AffyArrayQualityAnalysis_submit job.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="AffyArrayQualityAnalysis_pollPort" binding="tns:AffyArrayQualityAnalysis_pollBinding">
                 <wsdlsoap:address location="https://nugo-r.bioinformatics.nl/phenolink_nugo/biomoby/services/cgi-bin/LocalServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


