<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="AGILocusListInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="AGILocusListOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="AGILocusListPortType">
          <wsdl:operation name="AGILocusList">
                 <wsdl:input message="tns:AGILocusListInput"/>
                 <wsdl:output message="tns:AGILocusListOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="AGILocusListBinding" type="tns:AGILocusListPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="AGILocusList"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#AGILocusList' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="AGILocusListService">
          <wsdl:documentation>Authority: arabidopsis.org  -  returns a list of loci that are non-obsoleted from 
the TAIR database, can be limited by a  integer parameter for the number returned,
which defaults to 0 for all (or for as many as the service will allow in one query).</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="AGILocusListPort" binding="tns:AGILocusListBinding">
                 <wsdlsoap:address location="http://italy.stanford.edu:8090/tairservices/services/AGILocusList"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


