<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="BacMapTextSearchInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="BacMapTextSearchOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="BacMapTextSearchPortType">
          <wsdl:operation name="BacMapTextSearch">
                 <wsdl:input message="tns:BacMapTextSearchInput"/>
                 <wsdl:output message="tns:BacMapTextSearchOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="BacMapTextSearchBinding" type="tns:BacMapTextSearchPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="BacMapTextSearch"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#BacMapTextSearch' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="BacMapTextSearchService">
          <wsdl:documentation>Authority: ualberta.ca  -  U of A, Genome Canada, BacMap
http://wishart.biology.ualberta.ca/BacMap/
output is the blast results rendered in HTML</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="BacMapTextSearchPort" binding="tns:BacMapTextSearchBinding">
                 <wsdlsoap:address location="http://wishart.biology.ualberta.ca:8000/cgi-bin/MobyServer.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


