<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="Blast_Against_RefSeq_Complete_Sequenced_OrganismsInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="Blast_Against_RefSeq_Complete_Sequenced_OrganismsOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="Blast_Against_RefSeq_Complete_Sequenced_OrganismsPortType">
          <wsdl:operation name="Blast_Against_RefSeq_Complete_Sequenced_Organisms">
                 <wsdl:input message="tns:Blast_Against_RefSeq_Complete_Sequenced_OrganismsInput"/>
                 <wsdl:output message="tns:Blast_Against_RefSeq_Complete_Sequenced_OrganismsOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="Blast_Against_RefSeq_Complete_Sequenced_OrganismsBinding" type="tns:Blast_Against_RefSeq_Complete_Sequenced_OrganismsPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="Blast_Against_RefSeq_Complete_Sequenced_Organisms"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#Blast_Against_RefSeq_Complete_Sequenced_Organisms' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="Blast_Against_RefSeq_Complete_Sequenced_OrganismsService">
          <wsdl:documentation>Authority: mpiz-koeln.mpg.de  -  Runs a blastp search against the RefSeq database, which includes only complete sequenced organisms.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="Blast_Against_RefSeq_Complete_Sequenced_OrganismsPort" binding="tns:Blast_Against_RefSeq_Complete_Sequenced_OrganismsBinding">
                 <wsdlsoap:address location="http://bioinfo.mpiz-koeln.mpg.de/axis/services/Blast_Against_RefSeq_Complete_Sequenced_Organisms"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


