<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="DragonDB_TBLASTNInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="DragonDB_TBLASTNOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="DragonDB_TBLASTNPortType">
          <wsdl:operation name="DragonDB_TBLASTN">
                 <wsdl:input message="tns:DragonDB_TBLASTNInput"/>
                 <wsdl:output message="tns:DragonDB_TBLASTNOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="DragonDB_TBLASTNBinding" type="tns:DragonDB_TBLASTNPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="DragonDB_TBLASTN"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#DragonDB_TBLASTN' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="DragonDB_TBLASTNService">
          <wsdl:documentation>Authority: antirrhinum.net  -  Execute a blast of a protein FASTA sequence against a 6-frame translation of the DragonDB 
(Snapdragon; Antirrhinum majus) DNA sequence database</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="DragonDB_TBLASTNPort" binding="tns:DragonDB_TBLASTNBinding">
                 <wsdlsoap:address location="http://dev.biordf.net/mobyservices/services/DragonDB_TBLASTN"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


