<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="filterSequencesAndQualityDataByLengthInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="filterSequencesAndQualityDataByLengthOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="filterSequencesAndQualityDataByLengthPortType">
          <wsdl:operation name="filterSequencesAndQualityDataByLength">
                 <wsdl:input message="tns:filterSequencesAndQualityDataByLengthInput"/>
                 <wsdl:output message="tns:filterSequencesAndQualityDataByLengthOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="filterSequencesAndQualityDataByLengthBinding" type="tns:filterSequencesAndQualityDataByLengthPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="filterSequencesAndQualityDataByLength"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#filterSequencesAndQualityDataByLength' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="filterSequencesAndQualityDataByLengthService">
          <wsdl:documentation>Authority: genome.imim.es  -  Filters a set of sequences based on their length. Only sequences which length is greater than the length cutoff will be returned. It also filters out the quality data associated with the removed sequences.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="filterSequencesAndQualityDataByLengthPort" binding="tns:filterSequencesAndQualityDataByLengthBinding">
                 <wsdlsoap:address location="http://genome.imim.es/cgi-bin/moby/devel/MobyServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


