<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="fromXYDataTextToArrayFloatInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="fromXYDataTextToArrayFloatOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="fromXYDataTextToArrayFloatPortType">
          <wsdl:operation name="fromXYDataTextToArrayFloat">
                 <wsdl:input message="tns:fromXYDataTextToArrayFloatInput"/>
                 <wsdl:output message="tns:fromXYDataTextToArrayFloatOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="fromXYDataTextToArrayFloatBinding" type="tns:fromXYDataTextToArrayFloatPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="fromXYDataTextToArrayFloat"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#fromXYDataTextToArrayFloat' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="fromXYDataTextToArrayFloatService">
          <wsdl:documentation>Authority: inb.bsc.es  -  Get a molecular weight array from plain text (one weight per line).</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="fromXYDataTextToArrayFloatPort" binding="tns:fromXYDataTextToArrayFloatBinding">
                 <wsdlsoap:address location="http://inb.bsc.es/cgi-bin/mobyServices/dispatchers/Dispatcher.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


