<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="GeneIlluminator_GetGraphInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="GeneIlluminator_GetGraphOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="GeneIlluminator_GetGraphPortType">
          <wsdl:operation name="GeneIlluminator_GetGraph">
                 <wsdl:input message="tns:GeneIlluminator_GetGraphInput"/>
                 <wsdl:output message="tns:GeneIlluminator_GetGraphOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="GeneIlluminator_GetGraphBinding" type="tns:GeneIlluminator_GetGraphPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="GeneIlluminator_GetGraph"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#GeneIlluminator_GetGraph' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="GeneIlluminator_GetGraphService">
          <wsdl:documentation>Authority: www.bioinformatics.nl  -  Synchronous BioMOBY service for gene symbol disambiguation. If a gene symbol is ambiguous this service uses GeneIlluminator to create clusters describing which different genes sharing the same symbol exist in different parts of the tree of life. GeneIlluminator provides also aliases associated to the input gene symbol. Finally, an graphical overview of the clusters and gene symbols is created in SVG format and returned to the client. Have a look at the GeneIlluminator_GetClusters service if you want a textual representation of this data instead.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="GeneIlluminator_GetGraphPort" binding="tns:GeneIlluminator_GetGraphBinding">
                 <wsdlsoap:address location="https://www.bioinformatics.nl/phenolink/biomoby/services/cgi-bin/LocalServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


