<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getAgiLocusCodesForAffyATH1ProbesetIdInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getAgiLocusCodesForAffyATH1ProbesetIdOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getAgiLocusCodesForAffyATH1ProbesetIdPortType">
          <wsdl:operation name="getAgiLocusCodesForAffyATH1ProbesetId">
                 <wsdl:input message="tns:getAgiLocusCodesForAffyATH1ProbesetIdInput"/>
                 <wsdl:output message="tns:getAgiLocusCodesForAffyATH1ProbesetIdOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getAgiLocusCodesForAffyATH1ProbesetIdBinding" type="tns:getAgiLocusCodesForAffyATH1ProbesetIdPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getAgiLocusCodesForAffyATH1ProbesetId"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getAgiLocusCodesForAffyATH1ProbesetId' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getAgiLocusCodesForAffyATH1ProbesetIdService">
          <wsdl:documentation>Authority: ssg.uab.edu  -  Retrieve Agi Locus Code(s) for Affy Ath1 probesets.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getAgiLocusCodesForAffyATH1ProbesetIdPort" binding="tns:getAgiLocusCodesForAffyATH1ProbesetIdBinding">
                 <wsdlsoap:address location="http://138.26.144.5:8080/axis/services/getAgiLocusCodesForAffyATH1ProbesetId"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


