<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getAFAWEProteinIDBySequenceAndOrganismInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getAFAWEProteinIDBySequenceAndOrganismOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getAFAWEProteinIDBySequenceAndOrganismPortType">
          <wsdl:operation name="getAFAWEProteinIDBySequenceAndOrganism">
                 <wsdl:input message="tns:getAFAWEProteinIDBySequenceAndOrganismInput"/>
                 <wsdl:output message="tns:getAFAWEProteinIDBySequenceAndOrganismOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getAFAWEProteinIDBySequenceAndOrganismBinding" type="tns:getAFAWEProteinIDBySequenceAndOrganismPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getAFAWEProteinIDBySequenceAndOrganism"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getAFAWEProteinIDBySequenceAndOrganism' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getAFAWEProteinIDBySequenceAndOrganismService">
          <wsdl:documentation>Authority: mpiz-koeln.mpg.de  -  Returns the AFAWE (http://bioinfo.mpiz-koeln.mpg.de/afawe/) IDs for the given amino acid sequence and organism.
Please use as organism name the taxonomic name (e.g. "Arabidopsis thaliana" or "Homo sapiens") </wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getAFAWEProteinIDBySequenceAndOrganismPort" binding="tns:getAFAWEProteinIDBySequenceAndOrganismBinding">
                 <wsdlsoap:address location="http://bioinfo.mpiz-koeln.mpg.de/axis/services/getAFAWEProteinIDBySequenceAndOrganism"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


