<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getBinCodeBySGNInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getBinCodeBySGNOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getBinCodeBySGNPortType">
          <wsdl:operation name="getBinCodeBySGN">
                 <wsdl:input message="tns:getBinCodeBySGNInput"/>
                 <wsdl:output message="tns:getBinCodeBySGNOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getBinCodeBySGNBinding" type="tns:getBinCodeBySGNPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getBinCodeBySGN"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getBinCodeBySGN' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getBinCodeBySGNService">
          <wsdl:documentation>Authority: mapman.mpimp-golm.mpg.de  -  Get the MapMan BinCode for a specific item. The BinCode system is a heirarchical, redundancy reduced ontology of proteins, genes and metabolites. Please note that MapMan BinCodes are copyrighted, you may use them freely for academic purposes. However, you are not allowed to redistribute them without prior permission.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getBinCodeBySGNPort" binding="tns:getBinCodeBySGNBinding">
                 <wsdlsoap:address location="http://mapman.mpimp-golm.mpg.de/cgi-bin/dispatcher.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


