<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getColiCardIDs_by_SwissProtAccInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getColiCardIDs_by_SwissProtAccOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getColiCardIDs_by_SwissProtAccPortType">
          <wsdl:operation name="getColiCardIDs_by_SwissProtAcc">
                 <wsdl:input message="tns:getColiCardIDs_by_SwissProtAccInput"/>
                 <wsdl:output message="tns:getColiCardIDs_by_SwissProtAccOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getColiCardIDs_by_SwissProtAccBinding" type="tns:getColiCardIDs_by_SwissProtAccPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getColiCardIDs_by_SwissProtAcc"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getColiCardIDs_by_SwissProtAcc' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getColiCardIDs_by_SwissProtAccService">
          <wsdl:documentation>Authority: ualberta.ca  -  Given a Swiss-Prot accession, gets ColiCard identifiers for genes whose gene products are annotated as the protein that is identified by the accession number. ColiCards are E.coli gene summary pages contained in the CCDB database.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getColiCardIDs_by_SwissProtAccPort" binding="tns:getColiCardIDs_by_SwissProtAccBinding">
                 <wsdlsoap:address location="http://wishart.biology.ualberta.ca:8080/biomoby/services/getColiCardIDs_by_SwissProtAcc"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


