<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getColiCardIDsByKeywordInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getColiCardIDsByKeywordOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getColiCardIDsByKeywordPortType">
          <wsdl:operation name="getColiCardIDsByKeyword">
                 <wsdl:input message="tns:getColiCardIDsByKeywordInput"/>
                 <wsdl:output message="tns:getColiCardIDsByKeywordOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getColiCardIDsByKeywordBinding" type="tns:getColiCardIDsByKeywordPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getColiCardIDsByKeyword"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getColiCardIDsByKeyword' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getColiCardIDsByKeywordService">
          <wsdl:documentation>Authority: ualberta.ca  -  searchs the CCDB database and gets identifiers for ColiCards that match to the keyword</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getColiCardIDsByKeywordPort" binding="tns:getColiCardIDsByKeywordBinding">
                 <wsdlsoap:address location="http://wishart.biology.ualberta.ca:8080/biomoby/services/getColiCardIDsByKeyword"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


