<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getFlexAnalysisFromPCZInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getFlexAnalysisFromPCZOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getFlexAnalysisFromPCZPortType">
          <wsdl:operation name="getFlexAnalysisFromPCZ">
                 <wsdl:input message="tns:getFlexAnalysisFromPCZInput"/>
                 <wsdl:output message="tns:getFlexAnalysisFromPCZOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getFlexAnalysisFromPCZBinding" type="tns:getFlexAnalysisFromPCZPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getFlexAnalysisFromPCZ"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getFlexAnalysisFromPCZ' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getFlexAnalysisFromPCZService">
          <wsdl:documentation>Authority: mmb.pcb.ub.es  -  Extracts all kind of analysis from a PCASuite compressed trajectory, and returns it as a PCZ_Report</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getFlexAnalysisFromPCZPort" binding="tns:getFlexAnalysisFromPCZBinding">
                 <wsdlsoap:address location="http://inb.bsc.es/gn6/PCZAnalysis/getFlexAnalysisFromPCZ"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


