<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getGeneListFromDifferentialExpressionTestInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getGeneListFromDifferentialExpressionTestOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getGeneListFromDifferentialExpressionTestPortType">
          <wsdl:operation name="getGeneListFromDifferentialExpressionTest">
                 <wsdl:input message="tns:getGeneListFromDifferentialExpressionTestInput"/>
                 <wsdl:output message="tns:getGeneListFromDifferentialExpressionTestOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getGeneListFromDifferentialExpressionTestBinding" type="tns:getGeneListFromDifferentialExpressionTestPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getGeneListFromDifferentialExpressionTest"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getGeneListFromDifferentialExpressionTest' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getGeneListFromDifferentialExpressionTestService">
          <wsdl:documentation>Authority: bioinfo.cipf.es  -  This webservice extracts a list of genes from a differential expession test according to your input parameters: the list size and the extraction mode (from top to bottom, or from bottom to top)</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getGeneListFromDifferentialExpressionTestPort" binding="tns:getGeneListFromDifferentialExpressionTestBinding">
                 <wsdlsoap:address location="http://biomoby.bioinfo.cipf.es/cgi-bin/MobyServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


