<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getHingePointsWithDDMethodFromPCZ_ReportInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getHingePointsWithDDMethodFromPCZ_ReportOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getHingePointsWithDDMethodFromPCZ_ReportPortType">
          <wsdl:operation name="getHingePointsWithDDMethodFromPCZ_Report">
                 <wsdl:input message="tns:getHingePointsWithDDMethodFromPCZ_ReportInput"/>
                 <wsdl:output message="tns:getHingePointsWithDDMethodFromPCZ_ReportOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getHingePointsWithDDMethodFromPCZ_ReportBinding" type="tns:getHingePointsWithDDMethodFromPCZ_ReportPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getHingePointsWithDDMethodFromPCZ_Report"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getHingePointsWithDDMethodFromPCZ_Report' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getHingePointsWithDDMethodFromPCZ_ReportService">
          <wsdl:documentation>Authority: mmb.pcb.ub.es  -  Given a PCZ_Report and a desired principal component (0 for ALL), this service extracts Hinge Points with the "Dynamic Domain" method and returns the result of the clustering.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getHingePointsWithDDMethodFromPCZ_ReportPort" binding="tns:getHingePointsWithDDMethodFromPCZ_ReportBinding">
                 <wsdlsoap:address location="http://inb.bsc.es/gn6/FromPCZ/getHingePointsWithDDMethodFromPCZ_Report"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


