<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getKeggPathwaysByKeggIDInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getKeggPathwaysByKeggIDOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getKeggPathwaysByKeggIDPortType">
          <wsdl:operation name="getKeggPathwaysByKeggID">
                 <wsdl:input message="tns:getKeggPathwaysByKeggIDInput"/>
                 <wsdl:output message="tns:getKeggPathwaysByKeggIDOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getKeggPathwaysByKeggIDBinding" type="tns:getKeggPathwaysByKeggIDPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getKeggPathwaysByKeggID"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getKeggPathwaysByKeggID' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getKeggPathwaysByKeggIDService">
          <wsdl:documentation>Authority: bioinfo.icapture.ubc.ca  -  This service, given a KEGG identifier, attempts to retrieve KEGG pathways that that contain this ID.

For example, passing in:
hsa:6402

results in the following pathway returned: hsa04514.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getKeggPathwaysByKeggIDPort" binding="tns:getKeggPathwaysByKeggIDBinding">
                 <wsdlsoap:address location="http://es-01.chibi.ubc.ca/mobyservices/services/getKeggPathwaysByKeggID"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


