<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getNASCstockNameByLocusInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getNASCstockNameByLocusOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getNASCstockNameByLocusPortType">
          <wsdl:operation name="getNASCstockNameByLocus">
                 <wsdl:input message="tns:getNASCstockNameByLocusInput"/>
                 <wsdl:output message="tns:getNASCstockNameByLocusOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getNASCstockNameByLocusBinding" type="tns:getNASCstockNameByLocusPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getNASCstockNameByLocus"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getNASCstockNameByLocus' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getNASCstockNameByLocusService">
          <wsdl:documentation>Authority: arabidopsis.info  -  Retrieves the name of a stock for a given locus from the Nottingham Arabidopsis Stock Centre Germplasm database (http://arabidopsis.info). Example input: psv.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getNASCstockNameByLocusPort" binding="tns:getNASCstockNameByLocusBinding">
                 <wsdlsoap:address location="http://arabidopsis.info/cgi-bin/moby_services/Services/germplasm_services/germplasm_services.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


