<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getNASCArraysSlideByNASCstockCodeInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getNASCArraysSlideByNASCstockCodeOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getNASCArraysSlideByNASCstockCodePortType">
          <wsdl:operation name="getNASCArraysSlideByNASCstockCode">
                 <wsdl:input message="tns:getNASCArraysSlideByNASCstockCodeInput"/>
                 <wsdl:output message="tns:getNASCArraysSlideByNASCstockCodeOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getNASCArraysSlideByNASCstockCodeBinding" type="tns:getNASCArraysSlideByNASCstockCodePortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getNASCArraysSlideByNASCstockCode"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getNASCArraysSlideByNASCstockCode' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getNASCArraysSlideByNASCstockCodeService">
          <wsdl:documentation>Authority: arabidopsis.info  -  Retrieves slide names for a given NASC stock ocde from NASCArrays, Nottingham Arabidopsis Stock Centre's microarray database (http://affy.arabidopsis.info). Example input: N1093.</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getNASCArraysSlideByNASCstockCodePort" binding="tns:getNASCArraysSlideByNASCstockCodeBinding">
                 <wsdlsoap:address location="http://arabidopsis.info/cgi-bin/moby_services/Services/microarray_services/array_services.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


