<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getPrincipalComponentFromPCZ_ReportInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getPrincipalComponentFromPCZ_ReportOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getPrincipalComponentFromPCZ_ReportPortType">
          <wsdl:operation name="getPrincipalComponentFromPCZ_Report">
                 <wsdl:input message="tns:getPrincipalComponentFromPCZ_ReportInput"/>
                 <wsdl:output message="tns:getPrincipalComponentFromPCZ_ReportOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getPrincipalComponentFromPCZ_ReportBinding" type="tns:getPrincipalComponentFromPCZ_ReportPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getPrincipalComponentFromPCZ_Report"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getPrincipalComponentFromPCZ_Report' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getPrincipalComponentFromPCZ_ReportService">
          <wsdl:documentation>Authority: mmb.pcb.ub.es  -  Given the number of the principal component and the report, this service returns a collection of 4 FeatureAASequence objects for that component that later can be drawn</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getPrincipalComponentFromPCZ_ReportPort" binding="tns:getPrincipalComponentFromPCZ_ReportBinding">
                 <wsdlsoap:address location="http://inb.bsc.es/gn6/FromPCZ/getPrincipalComponentFromPCZ_Report"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


