<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getPubmedIDsByAGICodeInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getPubmedIDsByAGICodeOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getPubmedIDsByAGICodePortType">
          <wsdl:operation name="getPubmedIDsByAGICode">
                 <wsdl:input message="tns:getPubmedIDsByAGICodeInput"/>
                 <wsdl:output message="tns:getPubmedIDsByAGICodeOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getPubmedIDsByAGICodeBinding" type="tns:getPubmedIDsByAGICodePortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getPubmedIDsByAGICode"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getPubmedIDsByAGICode' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getPubmedIDsByAGICodeService">
          <wsdl:documentation>Authority: atidb.org  -  takes an AGI locus code and returns a collection of relevant Pubmed reference IDs where available</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getPubmedIDsByAGICodePort" binding="tns:getPubmedIDsByAGICodeBinding">
                 <wsdlsoap:address location="http://dev.biordf.net/~kawas/cgi-bin/EdMobyServer.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


