<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getProtProtInterfaceFromPDBIdInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getProtProtInterfaceFromPDBIdOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getProtProtInterfaceFromPDBIdPortType">
          <wsdl:operation name="getProtProtInterfaceFromPDBId">
                 <wsdl:input message="tns:getProtProtInterfaceFromPDBIdInput"/>
                 <wsdl:output message="tns:getProtProtInterfaceFromPDBIdOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getProtProtInterfaceFromPDBIdBinding" type="tns:getProtProtInterfaceFromPDBIdPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getProtProtInterfaceFromPDBId"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getProtProtInterfaceFromPDBId' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getProtProtInterfaceFromPDBIdService">
          <wsdl:documentation>Authority: mmb.pcb.ub.es  -  
		Given a pdbCode returns a prot-prot interface
	</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getProtProtInterfaceFromPDBIdPort" binding="tns:getProtProtInterfaceFromPDBIdBinding">
                 <wsdlsoap:address location="http://mmb2.pcb.ub.es:8080/PDBServices/getProtProtInterfaceFromPDBId"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


