<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getSymbolDefinitionsInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getSymbolDefinitionsOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getSymbolDefinitionsPortType">
          <wsdl:operation name="getSymbolDefinitions">
                 <wsdl:input message="tns:getSymbolDefinitionsInput"/>
                 <wsdl:output message="tns:getSymbolDefinitionsOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getSymbolDefinitionsBinding" type="tns:getSymbolDefinitionsPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getSymbolDefinitions"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getSymbolDefinitions' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getSymbolDefinitionsService">
          <wsdl:documentation>Authority: cnio.es  -  It returns all the sentences which define the iHOP gene or protein symbol related to the input</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getSymbolDefinitionsPort" binding="tns:getSymbolDefinitionsBinding">
                 <wsdlsoap:address location="http://ubio.bioinfo.cnio.es/biotools/iHOP/cgi-bin/iHOPMOBY"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


