<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="getStiffnessFromPCZ_ReportInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="getStiffnessFromPCZ_ReportOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="getStiffnessFromPCZ_ReportPortType">
          <wsdl:operation name="getStiffnessFromPCZ_Report">
                 <wsdl:input message="tns:getStiffnessFromPCZ_ReportInput"/>
                 <wsdl:output message="tns:getStiffnessFromPCZ_ReportOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="getStiffnessFromPCZ_ReportBinding" type="tns:getStiffnessFromPCZ_ReportPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="getStiffnessFromPCZ_Report"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#getStiffnessFromPCZ_Report' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="getStiffnessFromPCZ_ReportService">
          <wsdl:documentation>Authority: mmb.pcb.ub.es  -  Returns interresidue stiffness from PCZ_Report</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="getStiffnessFromPCZ_ReportPort" binding="tns:getStiffnessFromPCZ_ReportBinding">
                 <wsdlsoap:address location="http://inb.bsc.es/gn6/FromPCZ/getStiffnessFromPCZ_Report"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


