<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="HMDBSequenceSearchInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="HMDBSequenceSearchOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="HMDBSequenceSearchPortType">
          <wsdl:operation name="HMDBSequenceSearch">
                 <wsdl:input message="tns:HMDBSequenceSearchInput"/>
                 <wsdl:output message="tns:HMDBSequenceSearchOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="HMDBSequenceSearchBinding" type="tns:HMDBSequenceSearchPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="HMDBSequenceSearch"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#HMDBSequenceSearch' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="HMDBSequenceSearchService">
          <wsdl:documentation>Authority: ualberta.ca  -  U of A, Genome Canada, HMDB Sequence Search
http://www.hmdb.ca/hmdbBlast.html</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="HMDBSequenceSearchPort" binding="tns:HMDBSequenceSearchBinding">
                 <wsdlsoap:address location="http://wishart.biology.ualberta.ca:8000/cgi-bin/MobyServer.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


