<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="Locus2GoIDsInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="Locus2GoIDsOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="Locus2GoIDsPortType">
          <wsdl:operation name="Locus2GoIDs">
                 <wsdl:input message="tns:Locus2GoIDsInput"/>
                 <wsdl:output message="tns:Locus2GoIDsOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="Locus2GoIDsBinding" type="tns:Locus2GoIDsPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="Locus2GoIDs"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#Locus2GoIDs' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="Locus2GoIDsService">
          <wsdl:documentation>Authority: arabidopsis.org  -  returns a list of 1 or more go ids for a submitted AGI locus code from TAIR.  Also includes the evidence code and the reference id for the relationship, where the reference_id is a TAIR database accession</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="Locus2GoIDsPort" binding="tns:Locus2GoIDsBinding">
                 <wsdlsoap:address location="http://italy.stanford.edu:8090/tairservices/services/Locus2GoIDs"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


