<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="MOBYSHoundGiFromLocusIDListInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="MOBYSHoundGiFromLocusIDListOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="MOBYSHoundGiFromLocusIDListPortType">
          <wsdl:operation name="MOBYSHoundGiFromLocusIDList">
                 <wsdl:input message="tns:MOBYSHoundGiFromLocusIDListInput"/>
                 <wsdl:output message="tns:MOBYSHoundGiFromLocusIDListOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="MOBYSHoundGiFromLocusIDListBinding" type="tns:MOBYSHoundGiFromLocusIDListPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="MOBYSHoundGiFromLocusIDList"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#MOBYSHoundGiFromLocusIDList' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="MOBYSHoundGiFromLocusIDListService">
          <wsdl:documentation>Authority: bioinfo.icapture.ubc.ca  -  Fetches protein GI identifiers associated with a list of NCBI's LocusLink IDs (LocusID).</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="MOBYSHoundGiFromLocusIDListPort" binding="tns:MOBYSHoundGiFromLocusIDListBinding">
                 <wsdlsoap:address location="http://es-01.chibi.ubc.ca/mobyservices/services/MOBYSHoundGiFromLocusIDList"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


