<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="parseFromIntActInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="parseFromIntActOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="parseFromIntActPortType">
          <wsdl:operation name="parseFromIntAct">
                 <wsdl:input message="tns:parseFromIntActInput"/>
                 <wsdl:output message="tns:parseFromIntActOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="parseFromIntActBinding" type="tns:parseFromIntActPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="parseFromIntAct"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#parseFromIntAct' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="parseFromIntActService">
          <wsdl:documentation>Authority: pdg.cnb.uam.es  -  Translates from IntAct XML format to BioMoby Interaction format</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="parseFromIntActPort" binding="tns:parseFromIntActBinding">
                 <wsdlsoap:address location="http://www.pdg.cnb.uam.es/moby/cgi-bin/mobyservice"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


