<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:de.lmu.ifi.bio:pro-tag" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:de.lmu.ifi.bio:pro-tag" xmlns:intf="urn:de.lmu.ifi.bio:pro-tag" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:message name="checkForUpdateResponse">
		<wsdl:part name="checkForUpdateReturn" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="checkForUpdateRequest">
		<wsdl:part name="recentVersion" type="xsd:string"/>
	</wsdl:message>
	<wsdl:portType name="ProTagService">
		<wsdl:documentation>ProTag Update Service; see http://services.bio.ifi.lmu.de/prothesaurus/</wsdl:documentation>
		<wsdl:operation name="checkForUpdate" parameterOrder="recentVersion">
			<wsdl:documentation>Checks if there is a newer version of ProTag other than the version specified in the recentVersion parameter.</wsdl:documentation>
			<wsdl:input message="impl:checkForUpdateRequest" name="checkForUpdateRequest"/>
			<wsdl:output message="impl:checkForUpdateResponse" name="checkForUpdateResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="ProThesaurusSoapBinding" type="impl:ProTagService">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="checkForUpdate">
			<wsdlsoap:operation soapAction=""/>
			<wsdl:input name="checkForUpdateRequest">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:de.lmu.ifi.bio:pro-tag" use="encoded"/>
			</wsdl:input>
			<wsdl:output name="checkForUpdateResponse">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:de.lmu.ifi.bio:pro-tag" use="encoded"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="ProTagService">
		<wsdl:documentation>ProTag Update Service; see http://services.bio.ifi.lmu.de/prothesaurus/</wsdl:documentation>
		<wsdl:port binding="impl:ProThesaurusSoapBinding" name="ProThesaurus">
			<wsdlsoap:address location="http://services.bio.ifi.lmu.de:1046/prothesaurus/services/ProTagService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>