<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="runMatScanGFFCollectionVsInputMatricesInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="runMatScanGFFCollectionVsInputMatricesOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="runMatScanGFFCollectionVsInputMatricesPortType">
          <wsdl:operation name="runMatScanGFFCollectionVsInputMatrices">
                 <wsdl:input message="tns:runMatScanGFFCollectionVsInputMatricesInput"/>
                 <wsdl:output message="tns:runMatScanGFFCollectionVsInputMatricesOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="runMatScanGFFCollectionVsInputMatricesBinding" type="tns:runMatScanGFFCollectionVsInputMatricesPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="runMatScanGFFCollectionVsInputMatrices"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#runMatScanGFFCollectionVsInputMatrices' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="runMatScanGFFCollectionVsInputMatricesService">
          <wsdl:documentation>Authority: genome.imim.es  -  Analyzes a collection of DNA sequences for putative motifs (transcription or splicing factor binding sites) and reports them in GFF format. The collection of motifs is given by the user as a set of Position Weight Matrices (PWMs)</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="runMatScanGFFCollectionVsInputMatricesPort" binding="tns:runMatScanGFFCollectionVsInputMatricesBinding">
                 <wsdlsoap:address location="http://genome.imim.es/cgi-bin/moby/MobyServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


