<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="runNucleosomePotentialInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="runNucleosomePotentialOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="runNucleosomePotentialPortType">
          <wsdl:operation name="runNucleosomePotential">
                 <wsdl:input message="tns:runNucleosomePotentialInput"/>
                 <wsdl:output message="tns:runNucleosomePotentialOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="runNucleosomePotentialBinding" type="tns:runNucleosomePotentialPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="runNucleosomePotential"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#runNucleosomePotential' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="runNucleosomePotentialService">
          <wsdl:documentation>Authority: mmb.pcb.ub.es  -  This web service runs Nucleosome Potential for the given sequence. Note: the maximum allowed length for the sequence is 10,000 bps. Check additional documentation at http://mmb2.pcb.ub.es:8080/PhysicalProperties/runNucleosomePotential.html</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="runNucleosomePotentialPort" binding="tns:runNucleosomePotentialBinding">
                 <wsdlsoap:address location="http://mmb2.pcb.ub.es:8080/PhysicalProperties/runNucleosomePotential"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


