<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="runNCBIBlastp1Input">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="runNCBIBlastp1Output">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="runNCBIBlastp1PortType">
          <wsdl:operation name="runNCBIBlastp1">
                 <wsdl:input message="tns:runNCBIBlastp1Input"/>
                 <wsdl:output message="tns:runNCBIBlastp1Output"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="runNCBIBlastp1Binding" type="tns:runNCBIBlastp1PortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="runNCBIBlastp1"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#runNCBIBlastp1' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="runNCBIBlastp1Service">
          <wsdl:documentation>Authority: chirimoyo.ac.uma.es  -  Run NCBIBlast with default parameters from a fasta file</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="runNCBIBlastp1Port" binding="tns:runNCBIBlastp1Binding">
                 <wsdlsoap:address location="http://chirimoyo.ac.uma.es/cgi-bin/services/MobyEd_dispatcher.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


