<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="runOFunCUTInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="runOFunCUTOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="runOFunCUTPortType">
          <wsdl:operation name="runOFunCUT">
                 <wsdl:input message="tns:runOFunCUTInput"/>
                 <wsdl:output message="tns:runOFunCUTOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="runOFunCUTBinding" type="tns:runOFunCUTPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="runOFunCUT"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#runOFunCUT' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="runOFunCUTService">
          <wsdl:documentation>Authority: cnio.es  -  Analyzes the key functional annotations of the neighbor sequences related to the query sequence and makes the transference of the annotations, from clustering result (NCut) and sequence similitary search (ISSComplete, NCBI Blast)</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="runOFunCUTPort" binding="tns:runOFunCUTBinding">
                 <wsdlsoap:address location="http://ubio.bioinfo.cnio.es/inb/cgi-bin/MOBY-Services/INBServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


