<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="runPSIBlastpFromFASTAInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="runPSIBlastpFromFASTAOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="runPSIBlastpFromFASTAPortType">
          <wsdl:operation name="runPSIBlastpFromFASTA">
                 <wsdl:input message="tns:runPSIBlastpFromFASTAInput"/>
                 <wsdl:output message="tns:runPSIBlastpFromFASTAOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="runPSIBlastpFromFASTABinding" type="tns:runPSIBlastpFromFASTAPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="runPSIBlastpFromFASTA"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#runPSIBlastpFromFASTA' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="runPSIBlastpFromFASTAService">
          <wsdl:documentation>Authority: mmb.pcb.ub.es  -  Perform 2 iterations of protein PSI Blast against non-redundant database with standard settings</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="runPSIBlastpFromFASTAPort" binding="tns:runPSIBlastpFromFASTABinding">
                 <wsdlsoap:address location="http://mmb2.pcb.ub.es/moby/moby.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


