<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="runPhrapWithQualityDataInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="runPhrapWithQualityDataOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="runPhrapWithQualityDataPortType">
          <wsdl:operation name="runPhrapWithQualityData">
                 <wsdl:input message="tns:runPhrapWithQualityDataInput"/>
                 <wsdl:output message="tns:runPhrapWithQualityDataOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="runPhrapWithQualityDataBinding" type="tns:runPhrapWithQualityDataPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="runPhrapWithQualityData"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#runPhrapWithQualityData' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="runPhrapWithQualityDataService">
          <wsdl:documentation>Authority: genome.imim.es  -  Runs Phrap to Assemble a set of DNA sequences, taking into account base quality data</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="runPhrapWithQualityDataPort" binding="tns:runPhrapWithQualityDataBinding">
                 <wsdlsoap:address location="http://genome.imim.es/cgi-bin/moby/devel/MobyServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


