<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="runSIAMInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="runSIAMOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="runSIAMPortType">
          <wsdl:operation name="runSIAM">
                 <wsdl:input message="tns:runSIAMInput"/>
                 <wsdl:output message="tns:runSIAMOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="runSIAMBinding" type="tns:runSIAMPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="runSIAM"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#runSIAM' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="runSIAMService">
          <wsdl:documentation>Authority: cnio.es  -  SIAM (Statistical Inferred Annotation Model): Inferring Gene Ontology terms for FunCUT pipeline</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="runSIAMPort" binding="tns:runSIAMBinding">
                 <wsdlsoap:address location="http://ubio.bioinfo.cnio.es/inb/cgi-bin/MOBY-Services/INBServices.cgi"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


