<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="searchOrGuessSymbolIdFromInputInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="searchOrGuessSymbolIdFromInputOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="searchOrGuessSymbolIdFromInputPortType">
          <wsdl:operation name="searchOrGuessSymbolIdFromInput">
                 <wsdl:input message="tns:searchOrGuessSymbolIdFromInputInput"/>
                 <wsdl:output message="tns:searchOrGuessSymbolIdFromInputOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="searchOrGuessSymbolIdFromInputBinding" type="tns:searchOrGuessSymbolIdFromInputPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="searchOrGuessSymbolIdFromInput"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#searchOrGuessSymbolIdFromInput' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="searchOrGuessSymbolIdFromInputService">
          <wsdl:documentation>Authority: cnio.es  -  It looks for (if it is not possible, guess) an iHOP protein or gene symbol related to the input, and it is returned as a bare object</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="searchOrGuessSymbolIdFromInputPort" binding="tns:searchOrGuessSymbolIdFromInputBinding">
                 <wsdlsoap:address location="http://ubio.bioinfo.cnio.es/biotools/iHOP/cgi-bin/iHOPMOBY"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


