<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="seqretDNARefFASTA2GENBANKInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="seqretDNARefFASTA2GENBANKOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="seqretDNARefFASTA2GENBANKPortType">
          <wsdl:operation name="seqretDNARefFASTA2GENBANK">
                 <wsdl:input message="tns:seqretDNARefFASTA2GENBANKInput"/>
                 <wsdl:output message="tns:seqretDNARefFASTA2GENBANKOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="seqretDNARefFASTA2GENBANKBinding" type="tns:seqretDNARefFASTA2GENBANKPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="seqretDNARefFASTA2GENBANK"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#seqretDNARefFASTA2GENBANK' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="seqretDNARefFASTA2GENBANKService">
          <wsdl:documentation>Authority: soaplab.icapture.ubc.ca  -  EMBOSS seqret program

The sequence source is USA (Uniform Sequence Address).
This means that you pass in a database name as the namespace
and an entry from the db as the id, e.g. db = embl and id = X13776.
The input format is fasta
The output format is genbank</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="seqretDNARefFASTA2GENBANKPort" binding="tns:seqretDNARefFASTA2GENBANKBinding">
                 <wsdlsoap:address location="http://dev.biordf.net/mobyservices/services/seqretDNARefFASTA2GENBANK"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


