<?xml version="1.0" encoding="UTF-8"?>
<definitions name="termine" targetNamespace="urn:termine" xmlns:tns="urn:termine" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:termine" xmlns:SOAP="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:MIME="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:DIME="http://schemas.xmlsoap.org/ws/2002/04/dime/wsdl/" xmlns:WSDL="http://schemas.xmlsoap.org/wsdl/" xmlns="http://schemas.xmlsoap.org/wsdl/">

<types>

 <schema targetNamespace="urn:termine" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:termine" xmlns="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
  <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
 </schema>

</types>

<message name="analyze_request">
 <part name="src" type="xsd:string"/>
 <part name="input_format" type="xsd:string"/>
 <part name="output_format" type="xsd:string"/>
 <part name="stoplist" type="xsd:string"/>
 <part name="filter" type="xsd:string"/>
</message>

<message name="analyze_response">
 <part name="result" type="xsd:string"/>
</message>

<portType name="termine_porttype">
 <operation name="analyze">
  <documentation>Service definition of function analyze</documentation>
  <input message="tns:analyze_request"/>
  <output message="tns:analyze_response"/>
 </operation>
</portType>

<binding name="termine" type="tns:termine_porttype">
 <SOAP:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
 <operation name="analyze">
  <SOAP:operation style="rpc" soapAction=""/>
  <input>
     <SOAP:body use="encoded" namespace="urn:termine" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </input>
  <output>
     <SOAP:body use="encoded" namespace="urn:termine" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
  </output>
 </operation>
</binding>

<service name="termine"> 
 <port name="termine" binding="tns:termine">
  <SOAP:address location="http://www.nactem.ac.uk/termine"/>
 </port>
</service>

</definitions>
