<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://maya.ccg.unam.mx:8080/axis/TFmodellerService.jws" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://maya.ccg.unam.mx:8080/axis/TFmodellerService.jws" xmlns:intf="http://maya.ccg.unam.mx:8080/axis/TFmodellerService.jws" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->

   <wsdl:message name="TFmodellerRequest">

      <wsdl:part name="proteinFASTAsequence" type="xsd:string"/>

   </wsdl:message>

   <wsdl:message name="TFmodellerResponse">

      <wsdl:part name="TFmodellerReturn" type="xsd:string"/>

   </wsdl:message>

   <wsdl:portType name="TFmodellerService">

      <wsdl:operation name="TFmodeller" parameterOrder="proteinFASTAsequence">

         <wsdl:input message="impl:TFmodellerRequest" name="TFmodellerRequest"/>

         <wsdl:output message="impl:TFmodellerResponse" name="TFmodellerResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="TFmodellerServiceSoapBinding" type="impl:TFmodellerService">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="TFmodeller">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="TFmodellerRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://DefaultNamespace" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="TFmodellerResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://maya.ccg.unam.mx:8080/axis/TFmodellerService.jws" use="encoded"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="TFmodellerServiceService">

      <wsdl:port binding="impl:TFmodellerServiceSoapBinding" name="TFmodellerService">

         <wsdlsoap:address location="http://maya.ccg.unam.mx:8080/axis/TFmodellerService.jws"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
