<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<HTML><HEAD><TITLE>XSPAN - A Cross-Species Anatomy Project</TITLE>
<META content="text/html; charset=windows-1251" http-equiv=Content-Type>
<META name=DESCRIPTION 
content="XSPAN is a Cross-species anatomy project to design and build online anatomy and gene expression comparison tools.">
<META name=keywords 
content="XSPAN, cross-species anatomy, developmental anatomy, model embryos, ontology, gene expression, Heriot-Watt University, University of Edinburgh">
<META name=CLASSIFICATION 
content="Academic Institute, Research &amp; Development, Education, Bioinformatics, Biomedical Sciences">
<META name=SPECIALITY content="Scientific Research &amp; Development"><!-- Fireworks MX Dreamweaver MX target.  Created Mon Aug 25 11:28:00 GMT-2300 2003-->
<META name=GENERATOR content="MSHTML 8.00.6001.19120"></HEAD>
<BODY aLink=#666666 link=#666666 bgColor=#ffffff text=#333333 vLink=#999999>


<TABLE border=0 cellSpacing=0 cellPadding=0 width=710><!-- fwtable fwsrc="xspan_header_6.png" fwbase="xspan_header_6.jpg" fwstyle="Dreamweaver" fwdocid = "742308039" fwnested="1" -->
  <TBODY>
  <TR>
    <TD>
      <TABLE border=0 cellSpacing=0 cellPadding=0 width="87%">
        <TBODY>
        <TR>
          <TD width="42%"><A 
            href="http://www.xspan.org/"><IMG 
            id=xspan_logo border=0 name=xspan_logo alt="Xspan logo" 
            src="index_files/xspan.jpg" width=299 height=99></A></TD>
          <TD width="31%"><IMG src="index_files/header_space.jpg" width=220 
            height=99></TD>
          <TD width="4%"><A 
            href="http://www.ed.ac.uk/" rel="nofollow" 
            target=_blank><IMG id=u_of_ed_logo border=0 name=u_of_ed_logo 
            alt="University of Edinburgh logo" src="index_files/u_of_ed.jpg" 
            width=74 height=99></A></TD>
          <TD width="23%"><A 
            href="http://www.hw.ac.uk/" rel="nofollow" 
            target=_blank><IMG id=hw_logo border=0 name=hw_logo 
            alt="Heriot-Watt University logo" src="index_files/hw.jpg" width=117 
            height=99></A></TD></TR></TBODY></TABLE></TD></TR>
  <TR>
    <TD height=499>
      <TABLE border=0 cellSpacing=0 cellPadding=0 width="100%">
        <TBODY>
        <TR>
          <TD height=499 width="16%">
            <TABLE border=0 cellSpacing=0 cellPadding=0 width=710>
              <TBODY>
              <TR>
                <TD height=384 vAlign=top width=113>
                  <TABLE border=0 cellSpacing=0 cellPadding=0 width="100%">
                    <TBODY>
                    <TR>
                      <TD width="88%"><A 
                        href="http://www.xspan.org"><IMG 
                        id=home border=0 name=home alt=Home 
                        src="index_files/home.jpg" width=99 height=20></A></TD>
                      <TD width="12%"><IMG id=spacer_1 name=spacer_1 
                        alt="spacer gif" src="index_files/inner_side.jpg" 
                        width=15 height=20></TD></TR>
                    <TR>
                      <TD><IMG id=spacer_r3_c1 border=0 name=spacer_r3_c1 
                        alt="spacer gif" src="index_files/silver%2520edge.jpg" 
                        width=99 height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="overview.html"><IMG 
                        id=overview border=0 name=overview alt=Overview 
                        src="index_files/overview.jpg" width=99 
height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="technical.html"><IMG 
                        id=technical border=0 name=technical alt=Technical 
                        src="index_files/technical.jpg" width=99 
                      height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="interfaces.html"><IMG 
                        id=technical border=0 name=technical alt=XSPAN 
                        src="index_files/interfaces.jpg" width=99 
                      height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="cobra.html"><IMG 
                        id=technical border=0 name=technical alt=COBrA 
                        src="index_files/cobra_g.jpg" width=99 height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="sael.html"><IMG 
                        id=technical border=0 name=technical alt=SAEL 
                        src="index_files/sael.jpg" width=99 height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="cell_ontology.html"><IMG 
                        id=ontologies border=0 name=cell_ont alt="Cell Ontology" 
                        src="index_files/cell_ont.jpg" width=99 
height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="publications.html"><IMG 
                        id=publications border=0 name=publications 
                        alt=Publications src="index_files/pubs.jpg" width=99 
                        height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="people.html"><IMG 
                        id=people border=0 name=people alt=People 
                        src="index_files/people.jpg" width=99 height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="collaborators.html"><IMG 
                        id=collaborators border=0 name=collaborators 
                        alt=Collaborators src="index_files/collaborators.jpg" 
                        width=99 height=20></A></TD>
                      <TD><IMG id=spacer_1 name=spacer_1 alt="spacer gif" 
                        src="index_files/inner_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD><IMG border=0 name=xspan_header_6_r3_c1 alt="" 
                        src="index_files/silver%2520edge.jpg" width=99 
                      height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r9_c2 alt="" 
                        src="index_files/inner_tip.jpg" width=15 height=9></TD></TR>
                    <TR>
                      <TD><A 
                        href="contact.html"><IMG 
                        id=contact_us border=0 name=contact_us alt="Contact Us" 
                        src="index_files/contact.jpg" width=99 height=20></A></TD>
                      <TD><IMG border=0 name=xspan_header_6_r10_c2 alt="" 
                        src="index_files/bottom_side.jpg" width=15 
                    height=20></TD></TR>
                    <TR>
                      <TD height=9><IMG border=0 name=xspan_header_6_r11_c1 
                        alt="" src="index_files/white_edge.jpg" width=99 
                        height=9></TD>
                      <TD><IMG border=0 name=xspan_header_6_r11_c2 alt="" 
                        src="index_files/botton_tip.jpg" width=15 
                    height=9></TD></TR></TBODY></TABLE>
                  <TABLE border=0 cellSpacing=0 cellPadding=0 width="100%" 
                  height=207>
                    <TBODY>
                    <TR>
                      <TD>&nbsp;</TD></TR>
                    <TR>
                      <TD>&nbsp;</TD></TR>
                    <TR>
                      <TD>&nbsp;</TD></TR>
                    <TR>
                      <TD><A 
                        href="http://www.bbsrc.ac.uk/"  rel="nofollow"
                        target=_blank><IMG id=bbsrc_logo border=0 
                        name=bbsrc_logo alt="Funded by BBSRC logo" 
                        src="index_files/funded_bbsrc.jpg" width=114 
                        height=94></A></TD></TR>
                    <TR>
                      <TD>&nbsp;</TD></TR>
                    <TR>
                      <TD>&nbsp;</TD></TR></TBODY></TABLE></TD>
                <TD vAlign=top width=597>
                  <TABLE border=0 cellSpacing=0 cellPadding=20 width="100%">
                    <TBODY>
                    <TR>
                      <TD height=384>
                        <DIV align=center>
                        <P><FONT color=#333333 size=4 
                        face="Arial, Helvetica, sans-serif">Welcome to the XSPAN 
                        web site</FONT></P></DIV>
                        <P class=bodystyle align=center>&nbsp;</P>
                        <P class=bodystyle align=center><FONT color=#333333 
                        size=3 face="Arial, Helvetica, sans-serif">The overall 
                        objective of XSPAN is to support cross-species access to 
                        tissue-based genetic information through the development 
                        of an internet-based cross-species anatomy network, i.e. 
                        a cross-species anatomy ontology integration 
                        system.</FONT></P>
                        <P align=center><FONT color=#333333 size=3 
                        face="Arial, Helvetica, sans-serif">This system will 
                        provide interoperability between databases of key model 
                        embryos which will, in turn, facilitate access to gene 
                        expression and other tissue-based data across species, 
                        and to other genomics and proteomics 
                        resources.</FONT></P>
                        <P align=center><FONT color=#333333 size=3 
                        face="Arial, Helvetica, sans-serif">XSPAN is a joint 
                        project between the School of <A 
                        href="http://www.macs.hw.ac.uk/" rel="nofollow" 
                        target=_blank>Mathematical and Computer Sciences</A> at 
                        <A 
                        href="http://www.hw.ac.uk/" rel="nofollow" 
                        target=_blank>Heriot-Watt University</A>, and the 
                        Schools of <A 
                        href="http://www.bms.ed.ac.uk/" rel="nofollow" 
                        target=_blank>Biomedical Sciences</A> and <A 
                        href="http://www.informatics.ed.ac.uk/" rel="nofollow" 
                        target=_blank>Informatics</A> at the <A 
                        href="http://www.ed.ac.uk/" rel="nofollow" 
                        target=_blank>University of Edinburgh</A>.</FONT></P>
                        <P align=center><FONT color=#333333 size=3 
                        face="Arial, Helvetica, sans-serif">XSPAN is funded by 
                        the UK's Biotechnology and Biological Sciences Research 
                        Council (<A 
                        href="http://www.bbsrc.ac.uk/" rel="nofollow" 
                        target=_blank>BBSRC</A>)</FONT></P>
                        <P align=center><FONT color=#333333 size=3 
                        face="Arial, Helvetica, sans-serif">Click on the menus 
                        or any of the links above to see more about XSPAN, the 
                        people and the organisations involved in the 
                        project.</FONT></P></TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
            <TABLE border=0 cellSpacing=0 cellPadding=0 width="100%">
              <TBODY>
              <TR>
                <TD><IMG id=mac_made name=mac_made alt="Made on a Mac logo" 
                  src="index_files/mac_made_dark.jpg" width=114 height=30></TD></TR>
              <TR>
                <TD>&nbsp;</TD></TR>
              <TR>
                <TD>
                  <DIV align=center><FONT color=#333333 size=1 
                  face="Arial, Helvetica, sans-serif">Copyright 2011 http://www.xspan.org/.</FONT></DIV></TD></TR>
              <TR>
                <TD>&nbsp;</TD></TR>
              <TR>
                <TD height=15>
                  <DIV align=left><CENTER>
<a href="http://www.minzunews.net/">minzunews</a>
</CENTER>
</DIV></TD></TR></TBODY></TABLE></TD>
          <TD width="84%">&nbsp;</TD></TR></TBODY></TABLE></TD></TR></TBODY></TABLE>
          </BODY></HTML>
