<?xml version="1.0"?>
<wsdl:definitions name="MOBY_Central_Generated_WSDL"
                targetNamespace="http://biomoby.org/Central.wsdl"
                xmlns:tns="http://biomoby.org/Central.wsdl"
                xmlns:xsd1="http://biomoby.org/CentralXSDs.xsd"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/">

                 
  <wsdl:message name="ZhangInput">
          <wsdl:part name="data" type="xsd:string"/>
  </wsdl:message>

  <wsdl:message name="ZhangOutput">
          <wsdl:part name="body" type="xsd:string"/>
  </wsdl:message>

  <wsdl:portType name="ZhangPortType">
          <wsdl:operation name="Zhang">
                 <wsdl:input message="tns:ZhangInput"/>
                 <wsdl:output message="tns:ZhangOutput"/>
          </wsdl:operation>
  </wsdl:portType>
                
  <wsdl:binding name="ZhangBinding" type="tns:ZhangPortType">
          <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
          <wsdl:operation name="Zhang"><!-- in essense, this is the name of the subroutine that is called -->
                 <wsdlsoap:operation soapAction='http://biomoby.org/#Zhang' style='rpc'/>
                 <wsdl:input>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:input>
                 <wsdl:output>
                         <wsdlsoap:body use="encoded" namespace="http://biomoby.org/" encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"/>
                 </wsdl:output>
          </wsdl:operation>
  </wsdl:binding>
                
  <wsdl:service name="ZhangService">
          <wsdl:documentation>Authority: llama.med.harvard.edu  -  Pairs of genes whose expression profiles are correlated at a 
significance level of p=0.05 or better (lower = better).
</wsdl:documentation>  <!-- service description goes here -->
          <wsdl:port name="ZhangPort" binding="tns:ZhangBinding">
                 <wsdlsoap:address location="http://llama.med.harvard.edu/~fgibbons/cgi/BGN/dispatcher.pl"/>    <!-- URL to service scriptname -->
          </wsdl:port>
  </wsdl:service>

</wsdl:definitions>


